source 'https://rubygems.org'

gem 'aasm'
gem 'activerecord', '5.2.3'
gem 'active_model_serializers'
gem 'bcrypt'
gem 'carrierwave', '~> 2.0'
gem 'interactor', '~> 3.0'
gem 'kaminari-grape'
gem 'kaminari-activerecord'
gem 'grape'
gem 'grape-middleware-logger'
gem 'grape-active_model_serializers'
gem 'grape-kaminari'
gem 'grape-route-helpers'
gem 'mime-types'
gem 'pg'
gem 'puma'
gem 'seedbank'
gem 'standalone_migrations'

group :developemnt, :test do
  gem 'dotenv'
  gem 'faker'
  gem 'pry-byebug'
end

group :test do
  gem 'database_cleaner'
  gem 'factory_bot'
  gem 'fuubar'
  gem 'rack-test'
  gem 'rspec'
  gem 'simplecov'
end
